POST http://localhost:8080/rpc.test.Test/SHA256 HTTP/1.1
content-type: application/json

{
    "password": "abc123456"
}

POST http://localhost:8080/rpc.login.Login/Register HTTP/1.1
content-type: application/json

{
    "name": "Candy",
    "password": "abc123456"
}

POST http://localhost:8080/rpc.login.Login/Login HTTP/1.1
content-type: application/json

{
    "id": 3,
    "password": "abc123456"
}

POST  http://localhost:8080/rpc.user.User/GetUser HTTP/1.1
Authorization: 1 470cd62a-1fa8-4ff1-a188-b2279290d389
content-type: application/json

{
    "id": 1
}


POST  http://localhost:8080/getUsersByName?name='Bob' or 1=1 HTTP/1.1
Authorization: 1 470cd62a-1fa8-4ff1-a188-b2279290d389
content-type: application/json

{
    "name": "Bob"
}
