POST http://localhost:8080/rpc.test.Test/SHA256 HTTP/1.1
content-type: application/json

{
    "password": "abc123456"
}

POST http://localhost:8080/rpc.login.Login/Register HTTP/1.1
content-type: application/json

{
    "name": "Candy",
    "password": "abc123456"
}

POST http://localhost:8080/rpc.login.Login/Login HTTP/1.1
content-type: application/json

{
    "id": 3,
    "password": "abc123456"
}

POST  http://localhost:8080/rpc.user.User/GetUser HTTP/1.1
Authorization: 1 d0c75fd0-7441-484f-bbe7-d3a6beb01c37
content-type: application/json

{
    "id": 1
}


POST  http://localhost:8080/rpc.user.User/GetUsers HTTP/1.1
Authorization: 3 d0c75fd0-7441-484f-bbe7-d3a6beb01c37
content-type: application/json

{
    "name": "Bob"
}
