// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.28.3
// source: rpc/test/service.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SHA256Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SHA256Req) Reset() {
	*x = SHA256Req{}
	mi := &file_rpc_test_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SHA256Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SHA256Req) ProtoMessage() {}

func (x *SHA256Req) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SHA256Req.ProtoReflect.Descriptor instead.
func (*SHA256Req) Descriptor() ([]byte, []int) {
	return file_rpc_test_service_proto_rawDescGZIP(), []int{0}
}

func (x *SHA256Req) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SHA256Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SHA256Res) Reset() {
	*x = SHA256Res{}
	mi := &file_rpc_test_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SHA256Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SHA256Res) ProtoMessage() {}

func (x *SHA256Res) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SHA256Res.ProtoReflect.Descriptor instead.
func (*SHA256Res) Descriptor() ([]byte, []int) {
	return file_rpc_test_service_proto_rawDescGZIP(), []int{1}
}

func (x *SHA256Res) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

var File_rpc_test_service_proto protoreflect.FileDescriptor

var file_rpc_test_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x22, 0x27, 0x0a, 0x09, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x23, 0x0a, 0x09, 0x53,
	0x48, 0x41, 0x32, 0x35, 0x36, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32,
	0x35, 0x36, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36,
	0x32, 0x3a, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x53, 0x48, 0x41, 0x32,
	0x35, 0x36, 0x12, 0x13, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x48,
	0x41, 0x32, 0x35, 0x36, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x52, 0x65, 0x73, 0x42, 0x0a, 0x5a, 0x08,
	0x72, 0x70, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_test_service_proto_rawDescOnce sync.Once
	file_rpc_test_service_proto_rawDescData = file_rpc_test_service_proto_rawDesc
)

func file_rpc_test_service_proto_rawDescGZIP() []byte {
	file_rpc_test_service_proto_rawDescOnce.Do(func() {
		file_rpc_test_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_test_service_proto_rawDescData)
	})
	return file_rpc_test_service_proto_rawDescData
}

var file_rpc_test_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_test_service_proto_goTypes = []any{
	(*SHA256Req)(nil), // 0: rpc.test.SHA256Req
	(*SHA256Res)(nil), // 1: rpc.test.SHA256Res
}
var file_rpc_test_service_proto_depIdxs = []int32{
	0, // 0: rpc.test.Test.SHA256:input_type -> rpc.test.SHA256Req
	1, // 1: rpc.test.Test.SHA256:output_type -> rpc.test.SHA256Res
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_test_service_proto_init() }
func file_rpc_test_service_proto_init() {
	if File_rpc_test_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_test_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_test_service_proto_goTypes,
		DependencyIndexes: file_rpc_test_service_proto_depIdxs,
		MessageInfos:      file_rpc_test_service_proto_msgTypes,
	}.Build()
	File_rpc_test_service_proto = out.File
	file_rpc_test_service_proto_rawDesc = nil
	file_rpc_test_service_proto_goTypes = nil
	file_rpc_test_service_proto_depIdxs = nil
}
